version: '3.3'
services:
    gvm:
        volumes:
            - 'scanner:/data'
        environment:
            - 'MASTER_ADDRESS={IP'
            - MASTER_PORT=2222
        container_name: scanner
        image: 'securecompliance/gvm:scanner-{version}'
